name: "Transifex Push"

on:
  workflow_call:
    secrets:
      tx_token:
        required: true
    inputs:
      branch:
        required: false
        default: 'main'
        type: 'string'

jobs:
  ci:
    name: "Translations"
    runs-on: ubuntu-latest
    steps:

    ##########################################
    # Checkout repository                    #
    ##########################################
    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    ##########################################
    # Install depdendencies                  #
    ##########################################
    - name: Install Dependencies
      uses: php-actions/composer@v6
      with:
        dev: yes

    - name: Install xgettext
      run: sudo apt-get install gettext libgettextpo-dev

    ##########################################
    # Generate <plugin>.pot file             #
    ##########################################
    - name: "Generate <plugin>.pot file"
      run: ./vendor/bin/extract-locales


    ##########################################
    # Push transifiex source puglin.pot #
    ##########################################
    - name: Push source file (.pot)
      uses: transifex/cli-action@v2
      with:
        args: push
        token: ${{ secrets.tx_token }}
