name: "Transifex push sources"

on:
  workflow_call:
    secrets:
      transifex-token:
        required: true

jobs:
  transifex-push:
    name: "Push sources on Transifex"
    runs-on: "ubuntu-latest"
    container:
      image: "ghcr.io/glpi-project/githubactions-glpi-apache:latest"
      options: --user 1001 # using built-in image user, otherwise GitHub Actions can't write file to the container
    steps:

    - name: "Setup GLPI plugin"
      id: "setup-glpi-plugin"
      uses: "$/.github/actions/setup-glpi-plugin"

    - name: "Extract locales"
      working-directory: /var/www/glpi/
      run: |
        php bin/console tools:locales:extract --plugin=${{ steps.setup-glpi-plugin.outputs.plugin-key }}

    - name: "Push source file"
      uses: "transifex/cli-action@584fd205cbe598773b5a81ce711fa44842678189" # v2
      with:
        args: "push"
        token: "${{ secrets.transifex-token }}"
