name: "Transifex sync"

on:
  workflow_call:
    secrets:
      transifex-token:
        required: true
      github-token:
        required: true

jobs:
  transifex-sync:
    name: "Sync locales with Transifex"
    runs-on: "ubuntu-latest"
    container:
      image: "ghcr.io/glpi-project/githubactions-glpi-apache:latest"
      options: --user 1001 # using built-in image user, otherwise GitHub Actions can't write file to the container
    steps:

    - name: "Setup GLPI plugin"
      id: "setup-glpi-plugin"
      uses: "$/.github/actions/setup-glpi-plugin"

    - name: "Extract locales"
      working-directory: /var/www/glpi/
      run: |
        php bin/console tools:locales:extract --plugin=${{ steps.setup-glpi-plugin.outputs.plugin-key }}

    - name: "Push source file"
      uses: "transifex/cli-action@584fd205cbe598773b5a81ce711fa44842678189" # v2
      with:
        args: "push"
        token: "${{ secrets.transifex-token }}"

    - name: "Clean tmp directory"
      run: |
        rm -fr /tmp/tx

    - name: "Pull translations"
      uses: "transifex/cli-action@584fd205cbe598773b5a81ce711fa44842678189" # v2
      with:
        args: "pull --force --all --minimum-perc=80"
        token: "${{ secrets.transifex-token }}"

    - name: "Compile MO files"
      working-directory: /var/www/glpi/
      run: |
        php bin/console tools:locales:compile --plugin=${{ steps.setup-glpi-plugin.outputs.plugin-key }}

    - name: "Check status"
      id: "check-status"
      # en_GB.mo file will always be considered as updated as it is regenerated by the "tools:locales:extract" command.
      # It have to be ignore to prevent "empty" PRs to be generated.
      run: |
        if [ -n "$(git status --porcelain locales/*.mo ':(exclude)locales/en_GB.mo')" ]; then
          echo "CREATE_PR=yes" >> $GITHUB_OUTPUT
        else
          echo "CREATE_PR=no" >> $GITHUB_OUTPUT
        fi

    - name: "Create pull request"
      if: ${{ steps.check-status.outputs.CREATE_PR == 'yes' }}
      uses: "peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1" # v8.1.1
      with:
        commit-message: "Update locales"
        branch: "i18n-updates"
        branch-suffix: "timestamp"
        add-paths: "locales/"
        labels: "i18n"
        delete-branch: true
        title: "Chore(i18n): update translations"
        body: "Auto-updated translations files"
        # A PAT is required.
        # From https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow:
        # > When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN,
        # > with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run.
        # > This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes
        # > code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository
        # > contains a workflow configured to run when push events occur.
        token: ${{ secrets.github-token }}
