name: "Transifex Push"

on:
  workflow_call:
    secrets:
      tx_token:
        required: true
    inputs:
      branch:
        required: false
        default: 'main'
        type: 'string'

jobs:
  ci:
    name: "Translations"
    runs-on: ubuntu-latest
    steps:

    ##########################################
    # Checkout repository                    #
    ##########################################
    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    ##########################################
    # Install dependencies                  #
    ##########################################
    - name: Install Dependencies
      run: |
        sudo apt-get install gettext libgettextpo-dev python3-dev python3-pip libffi-dev libxml2-dev libxslt-dev git
        pip install lxml gitpython PyGithub termcolor

    ##########################################
    # Run composer                           #
    ##########################################
    - name: Install Composer Dependencies
      uses: php-actions/composer@v6
      with:
        dev: yes

    ##########################################
    # Generate <plugin>.pot file             #
    ##########################################
    - name: "Generate <plugin>.pot file"
      run: ./vendor/bin/extract-locales


    ##########################################
    # Push transifiex source puglin.pot #
    ##########################################
    - name: Push source file (.pot)
      uses: transifex/cli-action@v2
      with:
        args: push
        token: ${{ secrets.tx_token }}
