name: "Transifex push sources"

on:
  workflow_call:
    secrets:
      transifex-token:
        required: true

jobs:
  transifex-push:
    name: "Push sources on Transifex"
    runs-on: "ubuntu-latest"
    steps:

    - name: "Checkout"
      uses: "actions/checkout@v4"

    - name: "Install system dependencies"
      run: |
        sudo apt-get install gettext libgettextpo-dev python3-dev python3-pip libffi-dev libxml2-dev libxslt-dev git
        pip install lxml gitpython PyGithub termcolor

    - name: "Install composer dependencies"
      uses: "php-actions/composer@v6"
      with:
        dev: yes

    - name: "Extract locales"
      run: |
        ./vendor/bin/extract-locales

    - name: "Push source file"
      uses: "transifex/cli-action@v2"
      with:
        args: "push"
        token: "${{ secrets.transifex-token }}"
